### ISSUE TITLE
DVB: Crash

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#401]
This is processing BBC1 in real time exporting to .srt (doesn't happen to spupng when the OCR-to-comment is not used).  The backtrace (bottom of this post) seems useful.

410
00:03:04,140 --> 00:03:04,419
coming to Nice -- Nice Jazz Festival

*** Error in `/usr/local/src/ccextractor/linux/ccextractor': free(): invalid next size (fast): 0x0000000001b60e80 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7ffff6bb7725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7ffff6bbff4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ffff6bc3abc]
/usr/local/src/ccextractor/linux/ccextractor[0x43ba2d]
/usr/local/src/ccextractor/linux/ccextractor[0x44efe5]
/usr/local/src/ccextractor/linux/ccextractor[0x44c9f3]
/usr/local/src/ccextractor/linux/ccextractor[0x4567fb]
/usr/local/src/ccextractor/linux/ccextractor[0x456e16]
/usr/local/src/ccextractor/linux/ccextractor(main+0x407)[0x4062e4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ffff6b60830]
/usr/local/src/ccextractor/linux/ccextractor[0x405de9]
======= Memory map: ========
00400000-0058b000 r-xp 00000000 08:01 2229826                            /usr/local/src/ccextractor/linux/ccextractor
0078a000-0078b000 r--p 0018a000 08:01 2229826                            /usr/local/src/ccextractor/linux/ccextractor
0078b000-00791000 rw-p 0018b000 08:01 2229826                            /usr/local/src/ccextractor/linux/ccextractor
00791000-01c95000 rw-p 00000000 00:00 0                                  [heap]
7fffec000000-7fffec021000 rw-p 00000000 00:00 0
7fffec021000-7ffff0000000 ---p 00000000 00:00 0
7ffff2bfc000-7ffff4fb8000 rw-p 00000000 00:00 0
7ffff4fb8000-7ffff4fbb000 r-xp 00000000 08:01 7213505                    /lib/x86_64-linux-gnu/libdl-2.23.so
7ffff4fbb000-7ffff51ba000 ---p 00003000 08:01 7213505                    /lib/x86_64-linux-gnu/libdl-2.23.so
7ffff51ba000-7ffff51bb000 r--p 00002000 08:01 7213505                    /lib/x86_64-linux-gnu/libdl-2.23.so
7ffff51bb000-7ffff51bc000 rw-p 00003000 08:01 7213505                    /lib/x86_64-linux-gnu/libdl-2.23.so
7ffff51bc000-7ffff51c7000 r-xp 00000000 08:01 12722859                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7ffff51c7000-7ffff53c6000 ---p 0000b000 08:01 12722859                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7ffff53c6000-7ffff53c7000 r--p 0000a000 08:01 12722859                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7ffff53c7000-7ffff53ca000 rw-p 0000b000 08:01 12722859                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7ffff53ca000-7ffff53eb000 r-xp 00000000 08:01 7213548                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7ffff53eb000-7ffff55ea000 ---p 00021000 08:01 7213548                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7ffff55ea000-7ffff55eb000 r--p 00020000 08:01 7213548                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7ffff55eb000-7ffff55ec000 rw-p 00021000 08:01 7213548                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7ffff55ec000-7ffff5622000 r-xp 00000000 08:01 12723801                   /usr/lib/x86_64-linux-gnu/libopenjp2.so.2.1.0
7ffff5622000-7ffff5822000 ---p 00036000 08:01 12723801                   /usr/lib/x86_64-linux-gnu/libopenjp2.so.2.1.0
7ffff5822000-7ffff5823000 r--p 00036000 08:01 12723801                   /usr/lib/x86_64-linux-gnu/libopenjp2.so.2.1.0
7ffff5823000-7ffff5824000 rw-p 00037000 08:01 12723801                   /usr/lib/x86_64-linux-gnu/libopenjp2.so.2.1.0
7ffff5824000-7ffff587d000 r-xp 00000000 08:01 12723412                   /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7ffff587d000-7ffff5a7d000 ---p 00059000 08:01 12723412                   /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7ffff5a7d000-7ffff5a7e000 r--p 00059000 08:01 12723412                   /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7ffff5a7e000-7ffff5a80000 rw-p 0005a000 08:01 12723412                   /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7ffff5a80000-7ffff5aef000 r-xp 00000000 08:01 12723297                   /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4
7ffff5aef000-7ffff5cef000 ---p 0006f000 08:01 12723297                   /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4
7ffff5cef000-7ffff5cf0000 r--p 0006f000 08:01 12723297                   /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4
7ffff5cf0000-7ffff5cf3000 rw-p 00070000 08:01 12723297                   /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4
7ffff5cf3000-7ffff5d4a000 r-xp 00000000 08:01 12722863                   /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7ffff5d4a000-7ffff5f4a000 ---p 00057000 08:01 12722863                   /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7ffff5f4a000-7ffff5f4b000 r--p 00057000 08:01 12722863                   /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7ffff5f4b000-7ffff5f4c000 rw-p 00058000 08:01 12722863                   /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7ffff5f4c000-7ffff5f70000 r-xp 00000000 08:01 7213622                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7ffff5f70000-7ffff616f000 ---p 00024000 08:01 7213622                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7ffff616f000-7ffff6170000 r--p 00023000 08:01 7213622                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7ffff6170000-7ffff6171000 rw-p 00024000 08:01 7213622                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7ffff6171000-7ffff618a000 r-xp 00000000 08:01 7213672                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7ffff618a000-7ffff6389000 ---p 00019000 08:01 7213672                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7ffff6389000-7ffff638a000 r--p 00018000 08:01 7213672                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7ffff638a000-7ffff638b000 rw-p 00019000 08:01 7213672                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7ffff638b000-7ffff63a1000 r-xp 00000000 08:01 7213519                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff63a1000-7ffff65a0000 ---p 00016000 08:01 7213519                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff65a0000-7ffff65a1000 rw-p 00015000 08:01 7213519                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff65a1000-7ffff6713000 r-xp 00000000 08:01 12716028                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7ffff6713000-7ffff6913000 ---p 00172000 08:01 12716028                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7ffff6913000-7ffff691d000 r--p 00172000 08:01 12716028                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7ffff691d000-7ffff691f000 rw-p 0017c000 08:01 12716028                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7ffff691f000-7ffff6923000 rw-p 00000000 00:00 0
7ffff6923000-7ffff693b000 r-xp 00000000 08:01 7213627                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7ffff693b000-7ffff6b3a000 ---p 00018000 08:01 7213627                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7ffff6b3a000-7ffff6b3b000 r--p 00017000 08:01 7213627                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7ffff6b3b000-7ffff6b3c000 rw-p 00018000 08:01 7213627                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7ffff6b3c000-7ffff6b40000 rw-p 00000000 00:00 0
7ffff6b40000-7ffff6d00000 r-xp 00000000 08:01 7213481                    /lib/x86_64-linux-gnu/libc-2.23.so
7ffff6d00000-7ffff6eff000 ---p 001c0000 08:01 7213481                    /lib/x86_64-linux-gnu/libc-2.23.so
7ffff6eff000-7ffff6f03000 r--p 001bf000 08:01 7213481                    /lib/x86_64-linux-gnu/libc-2.23.so
7ffff6f03000-7ffff6f05000 rw-p 001c3000 08:01 7213481                    /lib/x86_64-linux-gnu/libc-2.23.so
7ffff6f05000-7ffff6f09000 rw-p 00000000 00:00 0
7ffff6f09000-7ffff7146000 r-xp 00000000 08:01 12723803                   /usr/lib/liblept.so.5.0.0
7ffff7146000-7ffff7345000 ---p 0023d000 08:01 12723803                   /usr/lib/liblept.so.5.0.0
7ffff7345000-7ffff7346000 r--p 0023c000 08:01 12723803                   /usr/lib/liblept.so.5.0.0
7ffff7346000-7ffff734c000 rw-p 0023d000 08:01 12723803                   /usr/lib/liblept.so.5.0.0
7ffff734c000-7ffff7635000 r-xp 00000000 08:01 12729068                   /usr/lib/libtesseract.so.3.0.4
7ffff7635000-7ffff7835000 ---p 002e9000 08:01 12729068                   /usr/lib/libtesseract.so.3.0.4
7ffff7835000-7ffff7839000 r--p 002e9000 08:01 12729068                   /usr/lib/libtesseract.so.3.0.4
7ffff7839000-7ffff783a000 rw-p 002ed000 08:01 12729068                   /usr/lib/libtesseract.so.3.0.4
7ffff783a000-7ffff7ace000 rw-p 00000000 00:00 0
7ffff7ace000-7ffff7bd6000 r-xp 00000000 08:01 7213551                    /lib/x86_64-linux-gnu/libm-2.23.so
7ffff7bd6000-7ffff7dd5000 ---p 00108000 08:01 7213551                    /lib/x86_64-linux-gnu/libm-2.23.so
7ffff7dd5000-7ffff7dd6000 r--p 00107000 08:01 7213551                    /lib/x86_64-linux-gnu/libm-2.23.so
7ffff7dd6000-7ffff7dd7000 rw-p 00108000 08:01 7213551                    /lib/x86_64-linux-gnu/libm-2.23.so
7ffff7dd7000-7ffff7dfd000 r-xp 00000000 08:01 7213453                    /lib/x86_64-linux-gnu/ld-2.23.so
7ffff7e05000-7ffff7fdf000 rw-p 00000000 00:00 0
7ffff7ff5000-7ffff7ff8000 rw-p 00000000 00:00 0
7ffff7ff8000-7ffff7ffa000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffa000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00025000 08:01 7213453                    /lib/x86_64-linux-gnu/ld-2.23.so
7ffff7ffd000-7ffff7ffe000 rw-p 00026000 08:01 7213453                    /lib/x86_64-linux-gnu/ld-2.23.so
7ffff7ffe000-7ffff7fff000 rw-p 00000000 00:00 0
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Program received signal SIGABRT, Aborted.
0x00007ffff6b75418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb)

(gdb) bt
#0  0x00007ffff6b75418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6b7701a in __GI_abort () at abort.c:89
#2  0x00007ffff6bb772a in __libc_message (do_abort=do_abort@entry=2,
    fmt=fmt@entry=0x7ffff6cd06b0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6bbff4a in malloc_printerr (ar_ptr=<optimised out>, ptr=<optimised out>,
    str=0x7ffff6cd0728 "free(): invalid next size (fast)", action=3) at malloc.c:5007
#4  _int_free (av=<optimised out>, p=<optimised out>, have_lock=0) at malloc.c:3868
#5  0x00007ffff6bc3abc in __GI___libc_free (mem=<optimised out>) at malloc.c:2969
#6  0x000000000043ba2d in freep (arg=0x7fffffffe8a0) at ../src/lib_ccx/ccx_common_common.c:65
#7  0x000000000044efe5 in write_cc_bitmap_as_srt (sub=0x1765f88, context=0xa16d50) at ../src/lib_ccx/ccx_encoders_srt.c:135
#8  0x000000000044c9f3 in encode_sub (context=0xa16d50, sub=0x1765f88) at ../src/lib_ccx/ccx_encoders_common.c:1416
#9  0x00000000004567fb in process_data (enc_ctx=0xa16d50, dec_ctx=0x1765f00, data_node=0xa15430)
    at ../src/lib_ccx/general_loop.c:669
#10 0x0000000000456e16 in general_loop (ctx=0x9dd670) at ../src/lib_ccx/general_loop.c:822
#11 0x00000000004062e4 in main (argc=6, argv=0x7fffffffec18) at ../src/ccextractor.c:152
(gdb)

**Comment by cfsmp3** [comment]
I've had it running without fail for days now processing BBC One in real time. Whatever the problem was it's definitely fixed.
