### ISSUE TITLE
DVB crash

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#745]
Streaming |  00:10TS continuity counter not incremented prev/curr 10/0
DVBSub error: line overflow
Unknown/unsupported pixel block 0x82
Unknown/unsupported pixel block 0x47
Unknown/unsupported pixel block 0x88
Unknown/unsupported pixel block 0x42
Unknown/unsupported pixel block 0x84
Unknown/unsupported pixel block 0x88
Unknown/unsupported pixel block 0x42
Unknown/unsupported pixel block 0x88
Unknown/unsupported pixel block 0x42
Unknown/unsupported pixel block 0xe
8-bit pixel string in 4-bit region!
Creating /mnt/tvcapturework/BBC2/_000002.txt
Creating /mnt/tvcapturework/BBC2/_000002_2.txt
TS continuity counter not incremented prev/curr 1/6
dvbsub_decode: incomplete, broken or empty packet
Streaming |  00:21
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) backtrace
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x000000000045c4a2 in paraof_ocrtext (sub=0x1745c80, crlf=0x1dab3d8 "\r\n", crlf_length=2) at ../src/lib_ccx/ocr.c:753
#2  0x000000000044b1f1 in write_cc_bitmap_as_transcript (sub=0x1745c80, context=0x1daac60)
    at ../src/lib_ccx/ccx_encoders_transcript.c:43
#3  0x000000000042516a in encode_sub (context=0x1daac60, sub=0x1745c80) at ../src/lib_ccx/ccx_encoders_common.c:1214
#4  0x000000000045f65b in dvbsub_decode (enc_ctx=0x17440b0, dec_ctx=0x1748a10, buf=0x1760792 "\017\020", buf_size=15,
    sub=0x1748a98) at ../src/lib_ccx/dvb_subtitle_decoder.c:1651
#5  0x000000000044d8f0 in process_data (enc_ctx=0x17440b0, dec_ctx=0x1748a10, data_node=0xa942c0)
    at ../src/lib_ccx/general_loop.c:650
#6  0x000000000044e83a in general_loop (ctx=0xa93140) at ../src/lib_ccx/general_loop.c:986
#7  0x0000000000407197 in main (argc=16, argv=0x7fffffffe438) at ../src/ccextractor.c:235
(gdb)

**Comment by cfsmp3** [comment]
Adding to this, finally caught something in valgrind:


something messy
==28690== Invalid read of size 1
==28690==    at 0x45A7CC: ocr_bitmap (in /usr/local/bin/ccextractor)
==28690==    by 0x45C2C6: ocr_rect (in /usr/local/bin/ccextractor)
==28690==    by 0x45F2BC: write_dvb_sub (in /usr/local/bin/ccextractor)
==28690==    by 0x45F8C0: dvbsub_decode (in /usr/local/bin/ccextractor)
==28690==    by 0x44D8EF: process_data (in /usr/local/bin/ccextractor)
==28690==    by 0x44E839: general_loop (in /usr/local/bin/ccextractor)
==28690==    by 0x407196: main (in /usr/local/bin/ccextractor)
==28690==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==28690==
==28690==
==28690== Process terminating with default action of signal 11 (SIGSEGV)
==28690==  Access not within mapped region at address 0x0
==28690==    at 0x45A7CC: ocr_bitmap (in /usr/local/bin/ccextractor)
==28690==    by 0x45C2C6: ocr_rect (in /usr/local/bin/ccextractor)
==28690==    by 0x45F2BC: write_dvb_sub (in /usr/local/bin/ccextractor)
==28690==    by 0x45F8C0: dvbsub_decode (in /usr/local/bin/ccextractor)
==28690==    by 0x44D8EF: process_data (in /usr/local/bin/ccextractor)
==28690==    by 0x44E839: general_loop (in /usr/local/bin/ccextractor)
==28690==    by 0x407196: main (in /usr/local/bin/ccextractor)
==28690==  If you believe this happened as a result of a stack
==28690==  overflow in your program's main thread (unlikely but
==28690==  possible), you can try to increase the size of the
==28690==  main thread stack using the --main-stacksize= flag.
==28690==  The main thread stack size used in this run was 8388608.
==28690==
==28690== HEAP SUMMARY:
==28690==     in use at exit: 219,433,569 bytes in 161,088 blocks
==28690==   total heap usage: 6,614,332 allocs, 6,453,244 frees, 13,937,861,610 bytes allocated
==28690==
==28690== LEAK SUMMARY:
==28690==    definitely lost: 461,762 bytes in 314 blocks
==28690==    indirectly lost: 37,376 bytes in 31 blocks
==28690==      possibly lost: 7,361,144 bytes in 404 blocks
==28690==    still reachable: 211,573,287 bytes in 160,339 blocks
==28690==                       of which reachable via heuristic:
==28690==                         newarray           : 3,986,944 bytes in 4,316 blocks
==28690==         suppressed: 0 bytes in 0 blocks
==28690== Rerun with --leak-check=full to see details of leaked memory
==28690==
==28690== For counts of detected and suppressed errors, rerun with: -v
==28690== ERROR SUMMARY: 565204 errors from 3 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

**Comment by cfsmp3** [comment]
I've replaced that "something messy" with an attempt to do at least skip the bitmap instead of crashing, but this definitely needs some peer review, to say the least :-)

**Comment by cfsmp3** [comment]
Closing - old report with no sample. 
Note to self: Next time, at least paste the command line.
